spin_manifest_version = 2

[application]
name = "prefer.social"
version = "0.1.0"
authors = ["Seungjin Kim <seungjin@duck.com>"]
description = "prefer.social activitypub based decentralized social service"

[variables]
redis_host = { required = true }
redis_credential = { required = true, secret = true }
redis_port = { required = true }
redis_channel = { required = true }
s3_access_key = { required = true, secret = true }
s3_secret_key = { required = true, secret = true }
s3_provider = { required = true }
s3_bucket = { required = true }
s3_endpoint = { required = true }
s3_region = { required = true }

[application.trigger.redis]
address = "redis://{{ redis_credential }}@{{ redis_host }}:{{ redis_port }}"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/latest/download/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]

[[trigger.http]]
route = "/.well-known/..."
component = "well-known"

[component.well-known]
source = { url = "https://github.com/prefer-social/prefer.social/releases/latest/download/well_known.wasm", digest = "sha256:" }
sqlite_databases = ["default"]
allowed_outbound_hosts = []
files = [{ source = "well-known/static", destination = "/" }]

[[trigger.http]]
route = "/..."
component = "web"

[component.web]
source = { url = "https://github.com/prefer-social/prefer.social/releases/latest/download/web.wasm", digest = "sha256:" }
sqlite_databases = ["default"]
allowed_outbound_hosts = ["https://*:*", "http://*:*"]

[[trigger.http]]
route = "/api/v1/..."
component = "api-v1"

[component.api-v1]
source = { url = "https://github.com/prefer-social/prefer.social/releases/latest/download/api_v1.wasm", digest = "sha256:" }
allowed_outbound_hosts = [
    "https://*:*",
    "redis://{{ redis_host }}:{{ redis_port }}",
    "rediss://{{ redis_host }}:{{ redis_port }}",
]
sqlite_databases = ["default"]
[component.api-v1.variables]
redis_host = "{{ redis_host }}"
redis_credential = "{{ redis_credential }}"
redis_port = "{{ redis_port }}"
redis_channel = "{{ redis_channel }}"
s3_access_key = "{{ s3_access_key }}"
s3_secret_key = "{{ s3_secret_key }}"
s3_provider = "{{ s3_provider }}"
s3_bucket = "{{ s3_bucket }}"
s3_endpoint = "{{ s3_endpoint }}"
s3_region = "{{ s3_region }}"


[[trigger.http]]
route = "/api/v2/..."
component = "api-v2"

[component.api-v2]
source = { url = "https://github.com/prefer-social/prefer.social/releases/latest/download/api_v2.wasm", digest = "sha256:" }
allowed_outbound_hosts = [
    "https://*:*",
    "redis://{{ redis_host }}:{{ redis_port }}",
    "rediss://{{ redis_host }}:{{ redis_port }}",
]
sqlite_databases = ["default"]

[component.api-v2.variables]
redis_host = "{{ redis_host }}"
redis_credential = "{{ redis_credential }}"
redis_port = "{{ redis_port }}"
redis_channel = "{{ redis_channel }}"
s3_access_key = "{{ s3_access_key }}"
s3_secret_key = "{{ s3_secret_key }}"
s3_provider = "{{ s3_provider }}"
s3_bucket = "{{ s3_bucket }}"
s3_endpoint = "{{ s3_endpoint }}"
s3_region = "{{ s3_region }}"

[[trigger.http]]
route = "/oauth/..."
component = "oauth"

[component.oauth]
source = { url = "https://github.com/prefer-social/prefer.social/releases/latest/download/oauth.wasm", digest = "sha256:" }
allowed_outbound_hosts = ["https://*:*"]
sqlite_databases = ["default"]

[[trigger.redis]]
channel = "{{ redis_channel }}"
component = "postbox"

[component.postbox]
source = { url = "https://github.com/prefer-social/prefer.social/releases/latest/download/postbox.wasm", digest = "sha256:" }
allowed_outbound_hosts = [
    "https://*:*",
    "http://*:*",
    "redis://{{ redis_host }}:{{ redis_port }}",
    "rediss://{{ redis_host }}:{{ redis_port }}",
]
sqlite_databases = ["default"]

[component.postbox.variables]
redis_host = "{{ redis_host }}"
redis_credential = "{{ redis_credential }}"
redis_port = "{{ redis_port }}"
redis_channel = "{{ redis_channel }}"
s3_access_key = "{{ s3_access_key }}"
s3_secret_key = "{{ s3_secret_key }}"
s3_provider = "{{ s3_provider }}"
s3_bucket = "{{ s3_bucket }}"
s3_endpoint = "{{ s3_endpoint }}"
s3_region = "{{ s3_region }}"
